### ISSUE TITLE
incompatible offsetUnset with ArrayManager in VotesManager

### ISSUE THREAD

**Issue by hboomsma** [julien-boudry/Condorcet#15]
```
Fatal error: Declaration of Condorcet\DataManager\VotesManager::offsetUnset($offset): void must be compatible with Condorcet\DataManager\ArrayManager::offsetUnset($offset): bool in vendor/julien-boudry/condorcet/lib/DataManager/VotesManager.php on line 18
```

**Comment by julien-boudry** [comment]
I can't reproduce it for a normal use.
The problem is, however, very real and should therefore produce this error, which I can not reproduce.
How did you trigger the error for your use?

However, I am merging your commit. It's better. Thanks.
Even if in principle: I will have to modify the method in the future, because this interface is not designed to return something (http://php.net/manual/en/arrayaccess.offsetunset.php). Perhaps I should rather throw an exception into the parent method and catch her on daughter instead returning a boolean ?

**Comment by hboomsma** [comment]
I found the defect when running the tests in our CI, There we also test the upcoming PHP release.
To reproduce use PHP 7.2.0 (not stable yet):
test.php
```php
<?php
include __DIR__ . '/vendor/autoload.php';
echo PHP_VERSION . PHP_EOL;
new \Condorcet\DataManager\VotesManager();
```
*output:*
```
$ phpnightly test.php 
7.2.0-dev

Fatal error: Declaration of Condorcet\DataManager\VotesManager::offsetUnset($offset): void must be compatible with Condorcet\DataManager\ArrayManager::offsetUnset($offset): bool in /home/hboomsma/projects/pnyx/www/vendor/julien-boudry/condorcet/lib/DataManager/VotesManager.php on line 18

Call Stack:
    0.0002     416624   1. {main}() /home/hboomsma/projects/pnyx/www/test.php:0
    0.0070     742656   2. spl_autoload_call() /home/hboomsma/projects/pnyx/www/test.php:4
    0.0070     742720   3. Composer\Autoload\ClassLoader->loadClass() /home/hboomsma/projects/pnyx/www/test.php:4
    0.0071     742880   4. Composer\Autoload\includeFile() /home/hboomsma/projects/pnyx/www/vendor/composer/ClassLoader.php:322
    0.0075     757064   5. include('/home/hboomsma/projects/pnyx/www/vendor/julien-boudry/condorcet/lib/DataManager/VotesManager.php') /home/hboomsma/projects/pnyx/www/vendor/composer/ClassLoader.php:444
```

**Comment by hboomsma** [comment]
BTW: Thnx, for your quick response.
Normally I would add an unit test showing the problem before fixing it, but since you did not have any testing platform in use I refrained from adding such a dependency. If you would like it, I could setup PHPUnit for your project and add some basic tests that could run in Travis.

**Comment by julien-boudry** [comment]
In fact, this problem seems to concern only PHP 7.2. And this correction solves it.
I also see others new warning with PHP 7.2 Nighlty build. But it may be a little early to assess them more precisely.

About **PHPUnit**.  This project from an amateurish developer (me). I do it for fun and level up, so iw was a little bit lazy about that kind of things. Preferring build my test as usage examples.

But I will be delighted to see initiatives on this subject ! You can start a new branch from dev-1.2.x branch. I will be delighted to watch this and merge it afterwards.
Many thanks.
