### ISSUE TITLE
New method: STAR Voting

### ISSUE THREAD

**Issue by hansioux** [julien-boudry/Condorcet#169]
There are many places where faith in an all electronic voting system is low, but hand counting for most fully condorcet compliant voting systems is impractical.  STAR (Score then Automatic Runoff) voting seems to be a decent half way point, where first round is simply adding up all the points, and the second round compares pairwise preference for the two candidates with the most points. 

It is currently being promoted by https://www.starvoting.org/

**Comment by julien-boudry** [comment]
![image](https://github.com/julien-boudry/Condorcet/assets/4020317/4c44e723-b8ba-4de3-a7b7-e45a67fbe201)

The method documentation is ambiguous on several points. Let me take this official example.

- Is there always 6 stars (no more, no less) regardless of the number of candidates?
- What should I do with Carmen and David in this example? 2 points each or 4 points each? So, whatever the answer, it's highly imperfect, as the number of points distributed per ballot is variable, opening the way to manipulation.

**Comment by LiamM32** [comment]
Well, saying that STAR is easier to count by hand is a strange argument to add it to a software for automatic vote-counting.

STAR is partially a cardinal voting method. Condorcet doesn't support cardinal voting. It doesn't have score voting because it only accepts rankings of candidates.

It's been awhile since I've been on top of Condorcet's development, but from what I remember, I think it would be difficult to rework it to accept cardinal voting methods.

**Comment by LiamM32** [comment]
To answer Julien's question, the number of stars does not depend on the number of candidates. STAR voting is a two-step process that combines score voting with one of the top-two candidates chosen by pairwise preference.
